#!/bin/bash
# Time: 2022-04-19 22:44:25
# Desc: ts_setup
[ -z "$TST_TS_TOPDIR" ] && export TST_TS_TOPDIR="$(realpath "$(dirname "$0")/..")"
source "${TST_TS_TOPDIR}/tst_common/lib/common.sh"

ts_setup() {
    # 测试套setup脚本，在这里增加setup操作
    msg "this is ts_setup"
    return 0
}

ts_setup
